name:                mysudoku
version:             0.1.0.0
github:              "githubuser/mysudoku"
license:             BSD3
author:              "Michael Nyika"
maintainer:          "mnyika@gmail.com"
copyright:           "2019 Michael Nyika"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mysudoku#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- containers

library:
  source-dirs: src

executables:
  mysudoku-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mysudoku

tests:
  mysudoku-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mysudoku
